# Generated by Django 5.1.1 on 2025-01-01 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
    ]
